
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anwar
 */
public class Inflected_Verb extends javax.swing.JFrame {

    /**
     * Creates new form Inflected_Verb
     */
    public Inflected_Verb() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        lbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jLabel3.setText("                     ቃል እዚህ ያስገቡ");

        txt1.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jButton1.setText("አውጣ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt2.setColumns(20);
        txt2.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        txt2.setRows(5);
        jScrollPane1.setViewportView(txt2);

        jButton2.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N
        jButton2.setText("አጽዳ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbl1.setFont(new java.awt.Font("Nyala", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(255, 255, 255)
                                .addComponent(jButton1)
                                .addGap(66, 66, 66)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txt1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter A word");
        } else {

            String text = txt1.getText();

            if (text.endsWith("ደ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "") + "ል").concat("  ታ" + text.replace("አ", "") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ደ", "ዳ") + "ል").concat("  ት" + text.replace("ደ", "ዳ") + "ለች").concat("  ይ" + text.replace("ደ", "ዳ") + "ሉ"));
                }
            } else if (text.endsWith("ጡ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text.replace("ጡ", "ጣ") + "ች").concat("  ያ" + text.replace("አ", "").replace("ጡ", "ጣ") + "ል").concat("  ታ" + text.replace("አ", "").replace("ጡ", "ጣ") + "ለች").concat("  አላ" + text.replace("አ", "").replace("ጡ", "ጣ") + "ችም").concat("  ያ" + text.replace("አ", "").replace("ጡ", "ጣ") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text.replace("ጡ", "ጣ") + "ች").concat("  ይ" + text.replace("ጡ", "ጣ") + "ል").concat("  ት" + text.replace("ጡ", "ጣ") + "ለች").concat("  ይ" + text.replace("ጡ", "ጣ") + "ሉ"));
                }
            } else if (text.endsWith("መ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "").replace("መ", "ማ") + "ል").concat("  ታ" + text.replace("አ", "").replace("መ", "ማ") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "").replace("መ", "ማ") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("መ", "ማ") + "ል").concat("  ት" + text.replace("መ", "ማ") + "ለች").concat("  ይ" + text.replace("መ", "ማ") + "ሉ"));
                }
            } else if (text.endsWith("ሰ") || text.endsWith("ሠ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "") + "ል").concat("  ታ" + text.replace("አ", "") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  " + text.replace("ለ", "ል")).concat("  ት" + text.replace("ሰ", "ሳ") + "ለች").concat("  ይ" + text.replace("ሰ", "ሳ") + "ሉ"));
                }
            } else if (text.endsWith("ሙ") || text.endsWith("ጡ") || text.endsWith("ዱ") || text.endsWith("ሉ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "") + "ል").concat("  ታ" + text.replace("አ", "") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text.replace("ሙ", "መ") + "ች").concat("  ይ" + text.replace("ሙ", "ማ") + "ል").concat("  ት" + text.replace("ሙ", "ማ") + "ለች").concat("  አል" + text.replace("ሙ", "ማ") + "ችም").concat("  ይ" + text.replace("ሙ", "ማ") + "ሉ"));
                }
            } else if (text.endsWith("ረ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "").replace("ረ", "ራ") + "ል").concat("  ት" + text.replace("ተ", "").replace("ረ", "ራ") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "").replace("ረ", "ራ") + "ሉ"));
                } else if (text.startsWith("አ")) {

                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "").replace("ረ", "ራ").replace("ለ", "ል") + "ል").concat("  ታ" + text.replace("አ", "").replace("ለ", "ል").replace("ረ", "ራ") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "").replace("ለ", "ል").replace("ረ", "ራ") + "ሉ"));

                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("መ", "ማ") + "ል").concat("  ት" + text.replace("መ", "ማ") + "ለች").concat("  ይ" + text.replace("መ", "ማ") + "ሉ"));
                }
            } else if (text.endsWith("ጠ")) {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "").replace("ጠ", "ጣ") + "ል").concat("  ት" + text.replace("ተ", "").replace("ጠ", "ጣ") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "").replace("ጠ", "ጣ") + "ሉ"));
                } else if (text.startsWith("አ")) {

                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "").replace("ጠ", "ጣ").replace("ለ", "ል") + "ል").concat("  ታ" + text.replace("አ", "").replace("ለ", "ል").replace("ጠ", "ጣ") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "").replace("ለ", "ል").replace("ጠ", "ጣ") + "ሉ"));

                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("መ", "ማ") + "ል").concat("  ት" + text.replace("መ", "ማ") + "ለች").concat("  ይ" + text.replace("መ", "ማ") + "ሉ"));
                }
            } else {
                if (text.startsWith("ተ")) {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text.replace("ተ", "") + "ል").concat("  ት" + text.replace("ተ", "") + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text.replace("ተ", "") + "ሉ"));
                } else if (text.startsWith("አ")) {
                    txt2.setText(("አላ" + text.replace("አ", "") + "ም").concat(" " + text + "ች").concat("  ያ" + text.replace("አ", "") + "ል").concat("  ታ" + text.replace("አ", "") + "ለች").concat("  አላ" + text.replace("አ", "") + "ችም").concat("  ያ" + text.replace("አ", "") + "ሉ"));
                } else {
                    txt2.setText(("አል" + text + "ም").concat(" " + text + "ች").concat("  ይ" + text + "ል").concat("  ት" + text + "ለች").concat("  አል" + text + "ችም").concat("  ይ" + text + "ሉ"));
                }
            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt1.setText("");
        txt2.setText("");
        lbl1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inflected_Verb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inflected_Verb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inflected_Verb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inflected_Verb.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inflected_Verb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextArea txt2;
    // End of variables declaration//GEN-END:variables
}
